import { createHmac, randomBytes } from 'node:crypto';

/**
 * Representation of an isolated authority node share within the threshold signing matrix.
 */
export interface AuthorityKeyShare {
    shareId: string;
    nodeName: string;
    secretFragment: string;
}

/**
 * Represents a partial cryptographic assertion fragment generated by a single independent authority node.
 */
export interface PartialSignatureFragment {
    shareId: string;
    signatureBlock: string;
}

/**
 * Manages threshold token signing operations requiring quorum consensus across independent authorities.
 * @author Kefmat
 * @version 1.0.0
 */
export class ThresholdSignatureEngine {
    private totalShares: number;
    private thresholdQuorum: number;
    private authorityShares: AuthorityKeyShare[] = [];

    /**
     * @param totalShares The total number of independent authority nodes configured (N).
     * @param thresholdQuorum The minimum number of valid fragments required to aggregate a signature (T).
     */
    constructor(totalShares: number = 5, thresholdQuorum: number = 3) {
        if (thresholdQuorum > totalShares) {
            throw new Error("INVALID_CONFIG: Threshold quorum cannot exceed total distributed shares.");
        }
        this.totalShares = totalShares;
        this.thresholdQuorum = thresholdQuorum;
        this.generateDistributedShares();
    }

    /**
     * Internal factory helper to distribute distinct cryptographic secret fragments across the cluster.
     */
    private generateDistributedShares(): void {
        for (let i = 1; i <= this.totalShares; i++) {
            this.authorityShares.push({
                shareId: `NODE-SHARE-00${i}`,
                nodeName: `auth-node-cluster-0${i}`,
                secretFragment: randomBytes(32).toString('hex')
            });
        }
    }

    /**
     * Retrieves the list of available authority shares to simulate distributed network topologies.
     */
    public getAvailableShares(): AuthorityKeyShare[] {
        return [...this.authorityShares];
    }

    /**
     * Instructs an isolated authority node to execute a partial cryptographic assertion over a token payload.
     * @param payload The canonical base64url token payload representation string.
     * @param share The unique key share allocated to the target node.
     * @returns A partial signature fragment verifying that node's independent validation.
     */
    public signPartial(payload: string, share: AuthorityKeyShare): PartialSignatureFragment {
        const signatureBlock = createHmac('sha256', share.secretFragment)
            .update(payload)
            .digest('hex');

        return { shareId: share.shareId, signatureBlock };
    }

    /**
     * Aggregates partial signature fragments into a unified threshold-certified cryptographic proof.
     * NOTE FOR THE NEXT PROGRAMMER: This method enforces strict quorum bounds. It must validate 
     * that all provided fragments originate from distinct nodes before checking if the count meets the
     * threshold threshold quorum. Duplicate share IDs must be discarded to prevent replay exploits.
     * @param payload The canonical token payload string that was signed.
     * @param fragments An array of partial signature fragments gathered across the authority cluster.
     * @returns A combined hexadecimal signature proof string representing quorum consensus.
     * @throws Error if the threshold is not met or if duplicate fragments are detected.
     */
    public aggregateThresholdSignature(payload: string, fragments: PartialSignatureFragment[]): string {
        const uniqueShareIds = new Set<string>();
        const filteredFragments: PartialSignatureFragment[] = [];

        for (const fragment of fragments) {
            if (!uniqueShareIds.has(fragment.shareId)) {
                uniqueShareIds.add(fragment.shareId);
                filteredFragments.push(fragment);
            }
        }

        if (filteredFragments.length < this.thresholdQuorum) {
            throw new Error(`QUORUM_FAILURE: Insufficient signature tokens. Gathered ${filteredFragments.length} unique shares, but a minimum of ${this.thresholdQuorum} is required.`);
        }

        // Deterministically sort fragments by share ID to guarantee identical aggregation outputs across gateways
        filteredFragments.sort((a, b) => a.shareId.localeCompare(b.shareId));

        // Aggregate the valid fragments using a secondary cryptographic hashing round
        const aggregationContext = filteredFragments.map(f => f.signatureBlock).join(':');
        return createHmac('sha256', aggregationContext)
            .update(payload)
            .digest('hex');
    }

    /**
     * Validates a completely synthesized threshold token signature at the Resource Server tier.
     * NOTE FOR THE NEXT PROGRAMMER: To verify the threshold signature out-of-band without 
     * re-contacting the individual nodes, the validator reconstructs the aggregated signature using 
     * the authoritative cluster fragments known to the security ledger state root context.
     */
    public verifyThresholdSignature(payload: string, signature: string, verifiedFragments: PartialSignatureFragment[]): boolean {
        try {
            const calculatedAggregation = this.aggregateThresholdSignature(payload, verifiedFragments);
            return calculatedAggregation === signature;
        } catch {
            return false;
        }
    }
}